### ISSUE TITLE
The new kube train fails to work as advertised

### ISSUE THREAD

**Issue by gr8sk8s** [inspec/train-k8s-container#16]
inspect detect with the new train (k8s-container) FAILS 

For example, running the following: 
❯ inspec detect -t k8s-container://kube-system/aws-node-bfbhd/aws-node
... results in: 
/Users/[USERNAME]/test/inspec2/train-k8s-container/lib/train/k8s/container/connection.rb:16:in `initialize': **undefined method `presence' for "kube-system":String (NoMethodError)**

# Describe the problem

Followed the installation instructions for the new kube k8s train, and tried to execute the "inspec detect -t k8s-container://<namespace/pod/container>" ... which failed.  Details below : 

1. First, cloned the repo : 
❯ git clone https://github.com/inspec/train-k8s-container.git

2. Next, ran the plugin install command: 
 ❯ inspec plugin install /Users/[username]/test/inspec2/train-k8s-container
... which succeeded 

3. Finally, attempted the "inspec detect -t k8s-container:// " command on an arbitrary namespace/pod/container, which FAILED with the following error: 
❯ inspec detect -t k8s-container://kube-system/aws-node-bfbhd/aws-node

/Users/[USERNAME]/test/inspec2/train-k8s-container/lib/train/k8s/container/connection.rb:16:in `initialize': **undefined method `presence' for "kube-system":String (NoMethodError)**
      from /Users/[USERNAME]/test/inspec2/train-k8s-container/lib/train/k8s/container/transport.rb:14:in `new'
      from /Users/[USERNAME]/test/inspec2/train-k8s-container/lib/train/k8s/container/transport.rb:14:in `connection'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.22.3/lib/inspec/backend.rb:38:in `create'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.22.3/lib/inspec/runner.rb:89:in `configure_transport'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.22.3/lib/inspec/runner.rb:81:in `initialize'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.22.3/lib/inspec/cli.rb:517:in `new'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.22.3/lib/inspec/cli.rb:517:in `run_command'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.22.3/lib/inspec/cli.rb:382:in `detect'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.22.3/lib/inspec/base_cli.rb:35:in `start'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-bin-5.22.3/bin/inspec:11:in `<top (required)>'
      from /usr/local/bin/inspec:275:in `load'
      from /usr/local/bin/inspec:275:in `<main>'

----

Tried this with other  namespace/pod/container ... all of which failed with the same error:  
... **undefined method `presence' for "<namespace>":String (NoMethodError)**

**Comment by ianbrinkerhoff** [comment]
`
def initialize(options)
          super(options)
          uri_path = options[:path]&.gsub(%r{^/}, "")
          @pod = options[:pod] || uri_path&.split("/")&.first
          @container_name = options[:container_name] || uri_path&.split("/")&.last
          @namespace = options[:namespace] || (options[:host] unless options[:host].nil? || options[:host].empty?)
          validate_parameters
          connect
end
`
-I had the same issue, it didn't like the presence method. I replace that with other code to check for empty namespace. Not sure if it's the best solution but it works.

This is the new initialize method in: train-k8s-container/lib/train/k8s/container/connection.rb

**Comment by Vasu1105** [comment]
Thanks @gr8sk8s and @ianbrinkerhoff. I addressed that in PR #17

**Comment by clintoncwolfe** [comment]
Yes - to be clear, this project is in early alpha development and is not intended to be complete.
